[package]
name = "puzzle2_1"
version = "0.1.0"
authors = ["Christian Griggs <christian.griggs@walmart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
